# 基本設定
workspace_dir: .
checkpoint_dir: checkpoints
output_dir: output
temp_dir: temp

# API設定
api:
  claude:
    model: claude-3-7-sonnet-20250219
    max_tokens: 200000
    temperature: 0.2
    timeout: 300
    retry_count: 3
    retry_delay: 5
  openai:
    model: gpt-4o-mini
    image_model: dall-e-3
    image_quality: standard
    image_size: 1024x1024
    temperature: 0.7
    timeout: 60
    retry_count: 3
    retry_delay: 5

# GitHub設定
github:
  owner: develogon
  repo: til
  branch: master
  commit_message_prefix: "[自動生成] "

# AWS S3設定
s3:
  bucket: develogon-til
  prefix: resources/
  region: ap-northeast-1
  public_url_base: https://s3.amazonaws.com/develogon-til

# Slack設定
slack:
  webhook_url: ""
  channel: "#general"
  username: "resource-generate-workflow"
  icon_emoji: ":robot_face:"

# プロンプト設定
prompts:
  system_prompt_dir: prompts/system
  message_prompt_dir: prompts/message

# テンプレート設定
templates:
  thumbnail_template: templates/thumbnail_template.yaml
  description_template: templates/description_template.md
  structure_template: templates/structure_template.yml

# 処理設定
processing:
  max_parallel_tasks: 4
  checkpoint_interval: 60  # 秒単位
  error_retry_count: 1
  error_retry_delay: 10 