# 開発環境設定
environment: development

# ログ設定
logging:
  level: DEBUG
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
# Redis設定
redis:
  url: "redis://localhost:6379/0"
  ttl: 3600
  max_connections: 10

# API設定
api:
  timeout: 30.0
  max_retries: 3
  
# Claude API
claude:
  rate_limit: 50
  model: "claude-3-sonnet-20240229"
  max_tokens: 4000
  temperature: 0.7

# OpenAI API
openai:
  model: "gpt-4"
  max_tokens: 4000
  temperature: 0.7

# ワーカー設定
workers:
  max_concurrent_tasks: 5
  batch_size: 20
  timeout: 300

# キャッシュ設定
cache:
  size: 500
  ttl: 1800

# メトリクス設定
metrics:
  enabled: true
  port: 8000
  path: "/metrics" 