environment: test
debug: true
max_concurrent_tasks: 3

workers:
  max_concurrent_tasks: 3
  counts:
    parser: 1
    ai: 1
    media: 1
    aggregator: 1

api:
  claude_api_key: "test_key"
  claude_model: "claude-3-sonnet-20240229"
  claude_rate_limit: 60
  openai_api_key: "test_key"
  openai_model: "gpt-4"
  timeout: 30.0
  max_retries: 3

storage:
  data_dir: "./data"
  output_dir: "./output"
  cache_dir: "./cache"
  log_dir: "./logs"

redis:
  url: "redis://localhost:6379/1"
  state_ttl: 3600
  checkpoint_ttl: 86400
  task_ttl: 86400

metrics_enabled: true
prometheus_port: 8001 